[tool.poetry]
name = "opsiclientd"
version = "4.2.0.0"
description = "opsi client daemon. The service running on opsi clients."
authors = ["Jan Schneider <j.schneider@uib.de>"]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
python-opsi = "^4.2.0"
tornado = "=4.3"

cffi = "^1.14.0"
[tool.poetry.dev-dependencies]
pyinstaller = "^3.6"

[tool.poetry.scripts]
opsiclientd = "opsiclientd.opsiclientdmain:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

