[tool.poetry]
name = "opsiclientd"
version = "4.2.0.123"
description = "opsi client daemon. The service running on opsi clients."
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
include = [
    "run-opsiclientd",
    "opsiclientd_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "https://pypi.uib.gmbh/simple"

[tool.poetry.dependencies]
python = "^3.10,<3.11"
autobahn = "^22.4"
distro = {platform = "linux", version = "^1.5"}
macholib = "^1.14"
msgpack = "^1.0"
netifaces = "^0.11"
pyelftools = "^0.28"
python-opsi = "^4.2.0.291"
python-opsi-common = "^4.2.0.263"
pywin32 = {platform = "win32", version = "^303"}
pywinpty = {platform = "win32", version = "^2.0"}
wmi = {platform = "win32", version = "^1.5"}
zeroconf = "^0.38"

[tool.poetry.dev-dependencies]
click = "8.0.4"  # pinned for tan to work (https://github.com/psf/black/issues/2964)
flake8 = "^4.0"
isort = "^5.10.1"
macholib = {version = "^1.14", platform = "darwin"}
mock = "^4.0"
mypy = "^0.950"
pefile = {version = "^2021.9", platform = "win32"}
pylint = "^2.5"
pytest = "^7.1"
pytest-cov = "^3.0"
pywin32-ctypes = {version = "^0.2", platform = "win32"}
requests = "^2.25"
tan = "^22.2"
pyinstaller = "^5.1"

[tool.poetry.scripts]
opsiclientd = "opsiclientd.__main__:opsiclientd"
opsiclientd_rpc = "opsiclientd.__main__:opsiclientd_rpc"
action_processor_starter = "opsiclientd.__main__:action_processor_starter"

[tool.black]
line-length = 140
target-version = ['py310']
use-tabs = true

[tool.isort]
profile = "black"
indent = "\t"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

