[tool.poetry]
name = "opsiclientd"
version = "4.2.0.0"
description = "opsi client daemon. The service running on opsi clients."
authors = ["Jan Schneider <j.schneider@uib.de>"]
include = [
    "opsiclientd_rpc",
    "run-opsiclientd",
    "gettext/*.mo"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
python-opsi = "^4.2.0.17"
#python-opsi = {path = "python-opsi"}

[tool.poetry.dev-dependencies]
pylint = "^2.5.0"
pyinstaller = "^3.6"
pywin32-ctypes = {version = "^0.2.0", platform = "win32"}
pefile = {version = "^2019.4.18", platform = "win32"}
macholib = {version = "^1.14", platform = "darwin"}

[tool.poetry.scripts]
opsiclientd = "opsiclientd.opsiclientdmain:main"
opsiclientd_rpc = "opsiclientd.opsiclientdrpc:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

