[tool.poetry]
name = "opsiclientd"
version = "4.2.0.56"
description = "opsi client daemon. The service running on opsi clients."
maintainers = ["uib GmbH <info@uib.de>"]
authors = ["uib GmbH <info@uib.de>"]
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
include = [
    "run-opsiclientd",
    "opsiclientd_data/**/*"
]

[[tool.poetry.source]]
name = "uibpypi"
url = "http://pypi.uib.gmbh:8080/simple"

[tool.poetry.dependencies]
python = "^3.7"
python-opsi = "^4.2.0.39"
#python-opsi = {path = "../python-opsi"}
pywin32 = {platform = "win32", version = "^227"}
wmi = {platform = "win32", version = "^1.5.1"}
distro = {platform = "linux", version = "^1.5.0"}
autobahn = "^20.7.1"
msgpack = "^1.0.0"
lz4 = "^3.1.1"

[tool.poetry.dev-dependencies]
pylint = "^2.5.0"
pywin32-ctypes = {version = "^0.2.0", platform = "win32"}
pefile = {version = "^2019.4.18", platform = "win32"}
macholib = {version = "^1.14", platform = "darwin"}
opsi-dev-tools = "^1.0.44"
pytest = "^5.4.3"
mock = "^4.0.2"
pytest-cov = "^2.10.0"
pyinstaller = "^4.0"

[tool.poetry.scripts]
opsiclientd = "opsiclientd.__main__:opsiclientd"
opsiclientd_rpc = "opsiclientd.__main__:opsiclientd_rpc"
action_processor_starter = "opsiclientd.__main__:action_processor_starter"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

