#!/usr/bin/env python3
"""
Main script to use with pyinstaller
"""

import sys
import traceback

try:
	from opsiclientd.__main__ import main

	main()
except SystemExit as err:
	sys.exit(err.code)
except KeyboardInterrupt:
	print("Interrupted", file=sys.stderr)
	sys.exit(1)
except Exception:  # pylint: disable=broad-except
	# Do not let pyinstaller handle exceptions and print:
	# "Failed to execute script run-opsiclientd"
	traceback.print_exc()
	sys.exit(1)
